"""Initial migration

Revision ID: d40295d22f92
Revises: 
Create Date: 2023-04-17 11:01:15.108439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd40295d22f92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_cafe')
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(length=250),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('map_url',
               existing_type=sa.TEXT(length=500),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('img_url',
               existing_type=sa.TEXT(length=500),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('location',
               existing_type=sa.TEXT(length=250),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('seats',
               existing_type=sa.TEXT(length=250),
               type_=sa.Integer(),
               nullable=False)
        batch_op.alter_column('coffee_price',
               existing_type=sa.TEXT(length=250),
               type_=sa.Float(),
               nullable=False)
        batch_op.create_foreign_key('fk_cafe_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cafe', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cafe_user', type_='foreignkey')
        batch_op.alter_column('coffee_price',
               existing_type=sa.Float(),
               type_=sa.TEXT(length=250),
               nullable=True)
        batch_op.alter_column('seats',
               existing_type=sa.Integer(),
               type_=sa.TEXT(length=250),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=250),
               existing_nullable=False)
        batch_op.alter_column('img_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(length=500),
               existing_nullable=False)
        batch_op.alter_column('map_url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(length=500),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(length=250),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('_alembic_tmp_cafe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('map_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('img_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), nullable=False),
    sa.Column('has_sockets', sa.BOOLEAN(), nullable=False),
    sa.Column('has_toilet', sa.BOOLEAN(), nullable=False),
    sa.Column('has_wifi', sa.BOOLEAN(), nullable=False),
    sa.Column('can_take_calls', sa.BOOLEAN(), nullable=False),
    sa.Column('seats', sa.INTEGER(), nullable=False),
    sa.Column('coffee_price', sa.FLOAT(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_cafe_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
